### ISSUE TITLE
Get rid of crypto

### ISSUE THREAD

**Issue by Michael-1** [sumwatshade/jest-transform-yaml#15]
The _crypto_ package is deprecated:

> This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**Comment by sumwatshade** [comment]
@Michael-1 I have updated this as of #16 and released [v1.0.0](https://www.npmjs.com/package/jest-transform-yaml) so I could lock down Node versions cleanly, thank you for reporting!
