### ISSUE TITLE
Jest 28 error: Invalid return value

### ISSUE THREAD

**Issue by hvasc** [sumwatshade/jest-transform-yaml#19]
this library's process is return object or string but return string is not support anymore

`process()` or/and `processAsync()` method of code transformer found at 
"/node_modules/jest-transform-yaml/lib/index.js" 
should return an object or a Promise resolving to an object. The object 
must have `code` property with a string of processed code.

FYI: https://jestjs.io/docs/upgrading-to-jest28#transformer

**Comment by naskio** [comment]
As a workaround you can use a wrapper around the library as following:

`jest.config.js`
```JavaScript
// ...
transform: {
// ...
	"^.+\\.ya?ml$": "<rootDir>/jest-yaml-transformer.js",
},
```

And add this wrapper to your `$rootDir/jest-yaml-transformer.js`

`jest-yaml-transformer.js`
```JavaScript
const transformer = require("jest-transform-yaml").default

const newTransformer = {
  ...transformer,
  process: function (...params) {
    return {
      code: transformer?.process(...params),
      map: null,
    }
  },
}

module.exports = newTransformer
```

**Comment by jaedb** [comment]
@naskio excellent pointer, saved me from much head scratching. Thanks!
